---
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#    enabled-by-default: false
myapp:
  val: ooh
  messenger: queue
  kafka:
    topicName: test-topic-one
#    bootstrapAddress: kafka-00:9092,kafka-01:9092,kafka-02:9092
    bootstrapAddress: 127.0.0.1:9092
#    bootstrapAddress: localhost:9092
spring:
  jmx:
    enabled: true
  config:
    activate:
      on-profile: default,dev
  cloud:
    bus:
      enabled: false
    discovery:
      enabled: false
    consul:
      enabled: false
      config:
        enabled: false
---
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jmx:
    enabled: true
  config:
    import: "consul:consul.ps.internal:8500"
    activate:
      on-profile: test
  application:
    name: k-producer
  cloud:
    consul:
      host: consul.ps.internal
      port: 8500
      scheme: http
      config:
        acl-token: anonymous
        enabled: true
        format: yaml
      discovery:
        health-check-interval: 15s
        health-check-url: http://k-producer.ps.internal/actuator/health
---
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jmx:
    enabled: true
  config:
    import: "consul:localhost:8500"
    activate:
      on-profile: ext
  application:
    name: k-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      scheme: http
      config:
        acl-token: anonymous
        enabled: true
      discovery:
        tags: app
        health-check-interval: 15s
        health-check-url: http://app.podspace.internal:8080/actuator/health
        metadata:
          metrics-path: /actuator/prometheus
