---
myapp:
  val: ooh
  kafka:
    topicName: test-topic-one
    bootstrapAddress: 192.168.1.60:9092
spring:
  jmx:
    enabled: true
  config:
    activate:
      on-profile: default,dev
  cloud:
    bus:
      enabled: false
    discovery:
      enabled: false
    consul:
      enabled: false
      config:
        enabled: false
---
spring:
  jmx:
    enabled: true
  config:
    import: "consul:consul.ps.internal:8500"
    activate:
      on-profile: test
  application:
    name: k-producer
  cloud:
    consul:
      host: consul.ps.internal
      port: 8500
      scheme: http
      config:
        acl-token: anonymous
        enabled: true
        format: yaml
