apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k-producer-ingress
  labels:
    app.kubernetes.io/name: k-producer
spec:
  ingressClassName: nginx
  rules:
    - host: k-producer.ps.internal
      http:
        paths:
          - backend:
              service:
                name: k-producer-service
                port:
                  number: 80
            pathType: Prefix
            path: /
