apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-ns
commonLabels:
  app.kubernetes.io/version: 0.3.1
resources:
  - service.yaml
  - ingress.yaml
  - service_account.yaml
